#!/bin/bash

clear
echo
echo "What is yor name"
echo
read a
echo

echo Hello $a 
echo

echo "Do you like working in tech? (y/n) "
read Like
echo

if [  `$Like`  == y ]
then
echo "You are cool"

elif [ `$Like` == n ]
then 
echo " You should try it, it's a good field"
fi
